#!/usr/bin/env python3
"""Builds the demo page the README screenshots are taken from.

Everything here is FICTIONAL — a made-up athlete, a made-up race, made-up
numbers. The real dashboard contains health data and a real race date, which
have no business in a public repository. This file exists so the screenshots
can be regenerated by anyone without exposing anyone.

The stylesheet is extracted verbatim from `harness/rapport.py`, so the demo
looks exactly like the real thing. If the real dashboard is restyled, re-run:

    python3 docs/demo/build_demo.py && open docs/demo/demo.html

then re-screenshot the six sections into docs/images/.
"""
from pathlib import Path

BASE = Path(__file__).resolve().parent
CSS = (BASE / "_style.css").read_text(encoding="utf-8")

# --------------------------------------------------------------------------
# The invented athlete. Deliberately unlike anyone real.
# --------------------------------------------------------------------------
RACE, RACE_DATE, TARGET = "Valencia Marathon", "Sunday, December 6, 2026", "3:29"
WEEKS = 24

W, H = 880, 260
PAD = {"l": 58, "r": 20, "t": 26, "b": 30}


def scale(vmin, vmax):
    span = (vmax - vmin) or 1
    return lambda v: H - PAD["b"] - (v - vmin) / span * (H - PAD["t"] - PAD["b"])


def y_axis(vmin, vmax, sy, fmt):
    out = []
    for i in range(4):
        v = vmin + (vmax - vmin) * i / 3
        y = sy(v)
        out.append(f'<line class="grid" x1="{PAD["l"]}" y1="{y:.1f}" x2="{W-PAD["r"]}" y2="{y:.1f}"/>')
        out.append(f'<text class="tick" x="{PAD["l"]-8}" y="{y+3:.1f}" text-anchor="end">{fmt(v)}</text>')
    return "".join(out)


def path_of(points):
    return "M" + " L".join(f"{x:.1f} {y:.1f}" for x, y in points)


def week_chart(title, subtitle, series, vmin, vmax, fmt=lambda v: f"{v:g}", colour="c-run"):
    sx = lambda s: PAD["l"] + (s - 1) / (WEEKS - 1) * (W - PAD["l"] - PAD["r"])
    sy = scale(vmin, vmax)
    parts = [y_axis(vmin, vmax, sy, fmt)]

    for s, label in [(4, "test"), (11, "retest"), (18, "tune-up"), (24, "RACE")]:
        x = sx(s)
        parts.append(f'<line class="jalon" x1="{x:.1f}" y1="{PAD["t"]}" x2="{x:.1f}" y2="{H-PAD["b"]}"/>')
        parts.append(f'<text class="jalon-txt" x="{x:.1f}" y="{PAD["t"]-6}" text-anchor="middle">{label}</text>')

    bar_w = (W - PAD["l"] - PAD["r"]) / WEEKS * 0.62
    for label, pts, style in series:
        pts = [(s, v) for s, v in pts if v is not None]
        if not pts:
            continue
        if style.startswith("bar"):
            cls = "bar-ref" if style == "bar_ref" else f"bar-reel {colour}"
            for s, v in pts:
                x, y = sx(s) - bar_w / 2, sy(v)
                parts.append(f'<rect class="{cls}" x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" '
                             f'height="{max(0, (H - PAD["b"]) - y):.1f}" rx="2"/>')
        else:
            cls = "line-ref" if style == "reference" else f"line-reel {colour}"
            parts.append(f'<path class="{cls}" d="{path_of([(sx(s), sy(v)) for s, v in pts])}"/>')
            if style == "real":
                for s, v in pts:
                    parts.append(f'<circle class="pt {colour}" cx="{sx(s):.1f}" cy="{sy(v):.1f}" r="4"/>')

    legend = "".join(
        f'<span class="lg"><i class="sw {"ref" if st in ("reference", "bar_ref") else colour}"></i>{lb}</span>'
        for lb, _, st in series)
    return f"""<figure class="card">
  <figcaption><h3>{title}</h3><p>{subtitle}</p></figcaption>
  <div class="legend">{legend}</div>
  <svg viewBox="0 0 {W} {H}" role="img" aria-label="{title}">{''.join(parts)}</svg>
</figure>"""


def day_chart(title, subtitle, values, vmin, vmax, fmt=lambda v: f"{v:g}", band=None, colour="c-blue"):
    n = len(values)
    sx = lambda i: PAD["l"] + i / max(1, n - 1) * (W - PAD["l"] - PAD["r"])
    sy = scale(vmin, vmax)
    parts = []
    if band:
        y1, y2 = sy(band[1]), sy(band[0])
        parts.append(f'<rect class="bande" x="{PAD["l"]}" y="{y1:.1f}" '
                     f'width="{W-PAD["l"]-PAD["r"]}" height="{y2-y1:.1f}"/>')
    parts.append(y_axis(vmin, vmax, sy, fmt))
    pts = [(sx(i), sy(v)) for i, v in enumerate(values)]
    parts.append(f'<path class="line-reel {colour}" d="{path_of(pts)}"/>')
    for x, y in pts:
        parts.append(f'<circle class="pt {colour}" cx="{x:.1f}" cy="{y:.1f}" r="3.5"/>')
    return f"""<figure class="card">
  <figcaption><h3>{title}</h3><p>{subtitle}</p></figcaption>
  <svg viewBox="0 0 {W} {H}" role="img" aria-label="{title}">{''.join(parts)}</svg>
</figure>"""


def dot_chart(title, subtitle, values, vmin, vmax, fmt, band):
    """Scatter over many nights — the sleep chart."""
    n = len(values)
    sx = lambda i: PAD["l"] + i / max(1, n - 1) * (W - PAD["l"] - PAD["r"])
    sy = scale(vmin, vmax)
    parts = []
    if band:
        y1, y2 = sy(band[1]), sy(band[0])
        parts.append(f'<rect class="bande" x="{PAD["l"]}" y="{y1:.1f}" '
                     f'width="{W-PAD["l"]-PAD["r"]}" height="{y2-y1:.1f}"/>')
    parts.append(y_axis(vmin, vmax, sy, fmt))
    for i, v in enumerate(values):
        parts.append(f'<circle class="pt c-blue" cx="{sx(i):.1f}" cy="{sy(v):.1f}" r="2.6"/>')
    return f"""<figure class="card">
  <figcaption><h3>{title}</h3><p>{subtitle}</p></figcaption>
  <svg viewBox="0 0 {W} {H}" role="img" aria-label="{title}">{''.join(parts)}</svg>
</figure>"""


def hhmm(minutes):
    return f"{int(minutes)//60}h{int(minutes)%60:02d}"


# --------------------------------------------------------------------------
# Invented series. Fixed arithmetic, no randomness — reproducible byte for byte.
# --------------------------------------------------------------------------
PLANNED = [32, 36, 39, 33, 42, 46, 49, 41, 52, 56, 44, 58, 62, 66, 52, 68,
           72, 58, 74, 78, 62, 66, 48, 34]
ACTUAL = [33, 35, 40, 33, 41, 46, 47, 42, 51, 55, 45, 57, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0]
ACTUAL = [v if v else None for v in ACTUAL]

# Efficiency: pace at 145 bpm, in seconds per km — improving slowly
EF = [round(352 - i * 1.35 + (3 if i % 4 == 0 else -2 if i % 3 == 0 else 0)) for i in range(12)]

WEIGHT_TARGET = [round(76.8 - i * 0.22, 1) for i in range(WEEKS)]
WEIGHT_REAL = [76.8, 76.4, 76.4, 75.9, 75.6, 75.5, 75.0, 74.8,
               74.6, 74.1, 74.0, 73.8]

SLEEP = [408 + ((i * 37) % 130) - 55 + (60 if i % 17 == 0 else 0) for i in range(312)]
HRV = [58, 55, 61, 57, 52, 59, 63, 60, 56, 54, 58, 62, 59, 57]
RHR = [51, 52, 50, 51, 53, 52, 50, 49, 51, 52, 54, 52, 51, 50]

OBSERVATIONS = [
    ("good", "Volume on track — 45 km this week",
     "45 km against 44 planned (102 %). Eleven weeks in a row within 10 % of plan. "
     "Consistency is what builds the result; a perfect single session is not."),
    ("warn", "Easy runs still too fast",
     "Average HR of 156 bpm on your two easy runs, against a 148 ceiling. This is the "
     "single most common mistake, and the one that costs the most: an easy run above "
     "threshold builds fatigue without building aerobic capacity."),
    ("good", "Pace at 145 bpm: 5:38/km",
     "Improved by 14 s/km over eleven weeks, temperature-corrected. This is the number "
     "that measures aerobic progress independently of weather and daily form."),
    ("", "Recovery within range",
     "HRV 59 ms inside your 47–72 baseline, resting HR 51, sleep 7h04. No sign of "
     "accumulated load. The coming week can carry its planned increase."),
]

SHOES = [
    dict(name="Nike Pegasus 41", use="road", km=743, maxi=800, state="warn",
         label="nearing end of life", icon="!",
         note="Limit reached around <strong>week 17</strong> if it carries the plan's full "
              "road volume. Order the replacement now, not the week it gives out.",
         meta="In service since 12/02/2026 · 71 runs · last on 22/08"),
    dict(name="Saucony Endorphin 4", use="road", km=96, maxi=700, state="ok",
         label="good condition", icon="✓",
         note="Covers the remaining 612 km of the plan.",
         meta="In service since 04/08/2026 · 9 runs · last on 24/08"),
]

PHASES = ["BASE", "BUILD", "SPECIFIC", "PEAK", "TAPER"]
GRID = [
    (1, "BASE", "Rebuild the aerobic base — nothing heroic", "3.4 hrs",
     [("REST", "Rest", ""), ("RUN", "Easy run", "48m"), ("STRENGTH", "Strength", "25m"),
      ("RUN", "Easy run", "44m"), ("REST", "Rest", ""), ("STRENGTH", "Strength #2", "25m"),
      ("RUN", "Long run — 14 km", "1h 32m")]),
    (2, "BASE", "Extend the long run, zero intensity", "3.8 hrs",
     [("REST", "Rest", ""), ("RUN", "Easy run", "52m"), ("STRENGTH", "Strength", "25m"),
      ("RUN", "Easy run", "49m"), ("REST", "Rest", ""), ("STRENGTH", "Strength #2", "25m"),
      ("RUN", "Long run — 16 km", "1h 45m")]),
    (3, "BASE", "Back to autumn volume + strides", "4.1 hrs",
     [("REST", "Rest", ""), ("RUN", "Easy + strides", "58m"), ("STRENGTH", "Strength", "25m"),
      ("RUN", "Easy run", "54m"), ("REST", "Rest", ""), ("STRENGTH", "Strength #2", "25m"),
      ("RUN", "Long run — 18 km", "1h 58m")]),
    (4, "BASE", "Down week + 30' THRESHOLD TEST (zone calibration)", "3.6 hrs",
     [("REST", "Rest", ""), ("RUN", "Easy + strides", "46m"), ("STRENGTH", "Strength", "30m"),
      ("RUN", "⚑ Threshold test 30'", "55m"), ("REST", "Rest", ""), ("STRENGTH", "Strength #2", "30m"),
      ("RUN", "Long run — 14 km", "1h 32m")]),
]
DAYS = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]


def section(anchor, inner):
    return f'<section id="{anchor}" class="shot">{inner}</section>'


def build():
    tabs = f"""<div class="tabbar">
  <div class="tabbar-title">{RACE} <span>· December 6, 2026 · target {TARGET}</span></div>
  <nav><a class="on">TRACKING</a><a>{WEEKS}-WEEK PROGRAMME</a></nav>
</div>"""

    obs = '<h2>This week</h2>\n<div class="obs-list">' + "".join(
        f'<div class="obs {e}"><h4>{t}</h4><p>{d}</p></div>' for e, t, d in OBSERVATIONS) + "</div>"

    volume = week_chart(
        "Weekly volume", "Planned kilometres (pale bars) against actual (solid). "
        "Consistency counts for more than the perfection of any single session.",
        [("PLANNED", list(enumerate(PLANNED, 1)), "bar_ref"),
         ("ACTUAL", list(enumerate(ACTUAL, 1)), "bar_real")],
        0, 84, lambda v: f"{v:.0f}")

    efficiency = week_chart(
        "Pace at 145 bpm", "Efficiency index extrapolated to a constant heart rate, "
        "corrected for temperature. The only measure of aerobic progress that weather "
        "cannot flatter.",
        [("PACE AT 145 BPM", list(enumerate(EF, 1)), "real")],
        330, 360, lambda v: f"{int(v)//60}:{int(v)%60:02d}", colour="c-gold")

    weight = week_chart(
        "Weight", "Actual against target trajectory. Roughly 1.4 min on the marathon per kilo.",
        [("TARGET", list(enumerate(WEIGHT_TARGET, 1)), "reference"),
         ("ACTUAL", list(enumerate(WEIGHT_REAL, 1)), "real")],
        70.5, 77.5, lambda v: f"{v:.1f}", colour="c-blue")

    sleep = dot_chart("Sleep", "Duration per night. Green band: your baseline over 312 nights "
                      "(6h40–7h30, mean 7h02).", SLEEP, 180, 620, hhmm, (400, 450))
    hrv = day_chart("Heart-rate variability (HRV)", "Green band: your Garmin baseline (47–72 ms). "
                    "Dropping below it signals accumulated fatigue.", HRV, 42, 78,
                    lambda v: f"{v:.0f}", (47, 72))
    rhr = day_chart("Resting heart rate", "Baseline 51 bpm. A sustained rise above 56 is a "
                    "fatigue or infection signal.", RHR, 45, 60, lambda v: f"{v:.0f}", (46, 56),
                    colour="c-gold")

    cards = []
    for s in SHOES:
        pct = s["km"] / s["maxi"] * 100
        cards.append(f"""<div class="shoe {s['state']}">
      <div class="shoe-head"><span class="shoe-name">{s['name']}<span class="use road">{s['use']}</span></span>
        <span class="shoe-tag"><i>{s['icon']}</i>{s['label']}</span></div>
      <div class="gauge"><div class="gauge-fill" style="width:{min(pct,100):.1f}%"></div></div>
      <div class="shoe-foot"><span><strong>{s['km']}</strong> / {s['maxi']} km</span>
        <span>{pct:.0f} %</span></div>
      <p class="shoe-note">{s['note']}</p>
      <p class="shoe-meta">{s['meta']}</p>
    </div>""")
    shoes = ('<h2>Shoes</h2>\n<div class="shoes">' + "".join(cards) + "</div>\n"
             '<p class="shoes-note">Thresholds are the ones set in your Garmin account. '
             '<strong>612 km</strong> of running left in the plan before the race.</p>')

    rows = []
    for num, phase, focus, hours, days in GRID:
        cells = []
        for i, (kind, name, dur) in enumerate(days):
            cls = {"RUN": "run", "STRENGTH": "strength", "REST": "rest"}[kind]
            cells.append(f'<div class="cell {cls}"><span class="k">{kind}</span>'
                         f'<span class="n">{name}</span>'
                         f'{f"<span class=d>{dur}</span>" if dur else ""}</div>')
        from datetime import date, timedelta
        depart = date(2026, 6, 22) + timedelta(days=(num - 1) * 7)
        head = "".join(f'<div class="dh">{d}<i>{(depart + timedelta(days=i)).day}</i></div>'
                       for i, d in enumerate(DAYS))
        rows.append(f"""<div class="wk">
  <div class="wk-head"><span class="wn">W{num}</span><span class="wp">{phase}</span>
    <span class="wf">{focus}</span><span class="wh">{hours}</span></div>
  <div class="wk-days">{head}</div>
  <div class="wk-cells">{''.join(cells)}</div>
</div>""")

    # NOTE : la section « programme » n'est plus capturée. Le README utilise la
    # capture publiée par le projet amont, qui montre SON viewer — reproduire
    # l'interface de quelqu'un d'autre de mémoire donnait un rendu inexact
    # (libellés de boutons inventés).
    programme = f"""<div class="prog">
  <aside class="prog-side">
    <h3>{RACE}</h3><p class="prog-date">{RACE_DATE}</p><p class="prog-name">Alex Rivera</p>
    <div class="ring"><span class="ring-v">46%</span><span class="ring-l">COMPLETE</span></div>
    <div class="prog-stats">
      <div><b>{WEEKS}</b><i>WEEKS</i></div><div><b>198</b><i>HOURS</i></div>
      <div><b>216</b><i>WORKOUTS</i></div><div><b>104</b><i>DAYS LEFT</i></div>
    </div>
    <div class="prog-btn"><b>Export Plan</b><i>Calendar, Zwift, Garmin, TrainerRoad</i></div>
  </aside>
  <div class="prog-main">
    <div class="phases">{''.join(f'<span class="ph{" on" if p=="BASE" else ""}">{p}</span>' for p in PHASES)}</div>
    {''.join(rows)}
  </div>
</div>"""

    extra = """
.shot { padding:26px 0; }
.tabbar { display:flex; align-items:center; justify-content:space-between;
  padding:14px 22px; border-bottom:1px solid var(--border-subtle); background:var(--bg-primary); }
.tabbar-title { font-family:var(--serif); font-size:19px; font-weight:600; }
.tabbar-title span { font-family:var(--mono); font-size:11px; color:var(--accent); font-weight:400; }
.tabbar nav { display:flex; gap:26px; font-family:var(--mono); font-size:10.5px;
  letter-spacing:.12em; color:var(--text-muted); }
.tabbar nav .on { color:var(--text-primary); border-bottom:2px solid var(--accent); padding-bottom:5px; }
.obs-list { display:grid; gap:11px; }
.prog { display:grid; grid-template-columns:230px 1fr; gap:22px; }
.prog-side { background:var(--bg-secondary); border:1px solid var(--border-subtle);
  border-radius:14px; padding:22px 18px; text-align:center; }
.prog-side h3 { font-family:var(--serif); font-size:21px; margin:0 0 6px; }
.prog-date { font-family:var(--mono); font-size:11px; color:var(--accent); margin:0 0 4px; }
.prog-name { font-size:13px; color:var(--text-muted); margin:0 0 20px; }
.ring { width:104px; height:104px; margin:0 auto 20px; border-radius:50%;
  border:3px solid var(--border-medium); display:flex; flex-direction:column;
  align-items:center; justify-content:center; }
.ring-v { font-size:26px; font-weight:600; }
.ring-l { font-family:var(--mono); font-size:8.5px; letter-spacing:.12em; color:var(--text-muted); }
.prog-stats { display:grid; grid-template-columns:1fr 1fr; gap:9px; margin-bottom:18px; }
.prog-stats div { background:var(--bg-tertiary); border-radius:9px; padding:11px 4px; }
.prog-stats b { display:block; font-size:19px; }
.prog-stats i { font-family:var(--mono); font-size:8px; letter-spacing:.11em;
  color:var(--text-muted); font-style:normal; }
.prog-btn { background:linear-gradient(135deg,#f59e0b,#f97316); border-radius:10px;
  padding:13px 10px; color:#1a1205; }
.prog-btn b { display:block; font-size:14px; }
.prog-btn i { font-size:9.5px; font-style:normal; opacity:.8; }
.phases { display:flex; gap:7px; margin-bottom:15px; }
.ph { flex:1; text-align:center; padding:8px; border-radius:8px; background:var(--bg-tertiary);
  font-family:var(--mono); font-size:9.5px; letter-spacing:.1em; color:var(--text-secondary); }
.ph.on { background:var(--blue); color:#fff; }
.wk { background:var(--bg-secondary); border:1px solid var(--border-subtle);
  border-radius:12px; padding:14px 16px; margin-bottom:11px; }
.wk-head { display:flex; align-items:center; gap:11px; margin-bottom:11px; }
.wn { background:var(--bg-elevated); border-radius:5px; padding:2px 7px;
  font-family:var(--mono); font-size:9.5px; }
.wp { font-family:var(--mono); font-size:10px; letter-spacing:.1em; }
.wf { flex:1; font-size:12.5px; color:var(--text-muted); }
.wh { font-family:var(--mono); font-size:11px; color:var(--text-secondary); }
.wk-days, .wk-cells { display:grid; grid-template-columns:repeat(7,1fr); gap:7px; }
.dh { font-family:var(--mono); font-size:9px; letter-spacing:.1em; color:var(--text-muted);
  display:flex; justify-content:space-between; padding:0 3px 5px; }
.dh i { font-style:normal; }
.cell { border-radius:8px; padding:9px 8px; min-height:64px; border-left:3px solid; }
.cell .k { display:block; font-family:var(--mono); font-size:8px; letter-spacing:.1em;
  margin-bottom:3px; }
.cell .n { display:block; font-size:11.5px; line-height:1.35; }
.cell .d { display:block; font-family:var(--mono); font-size:9px; color:var(--text-muted);
  margin-top:4px; }
.cell.run { background:rgba(249,115,22,.11); border-color:var(--run); }
.cell.run .k { color:var(--run); }
.cell.strength { background:rgba(168,85,247,.11); border-color:var(--strength); }
.cell.strength .k { color:var(--strength); }
.cell.rest { background:var(--bg-tertiary); border-color:var(--rest); }
.cell.rest .k, .cell.rest .n { color:var(--text-muted); }
"""

    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>Monday Coach — demo (fictional data)</title>
<style>{CSS}{extra}</style></head><body><div class="wrap">
{section("tabs-bar", tabs)}
{section("observations", obs)}
{section("volume", volume)}
{section("efficiency", efficiency + weight)}
{section("recovery", sleep + hrv + rhr)}
{section("shoes", shoes)}
</div></body></html>"""


if __name__ == "__main__":
    out = BASE / "demo.html"
    out.write_text(build(), encoding="utf-8")
    print(f"{out.relative_to(BASE.parent.parent)} — {out.stat().st_size // 1024} KB")
    print("Sections: tabs-bar · observations · volume · recovery · shoes · programme")
